CREATE DATABASE IF NOT EXISTS financial_db;
USE financial_db;
-- 个人财务管理 API - 数据库表结构
-- 基于你的设计：用户表、账单表、分类表
CREATE TABLE users (
    name VARCHAR(50) NOT NULL,
    PASSWORD_HASH VARCHAR(256) NOT NULL,
    USER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);
CREATE TABLE CATEGORIES (
    USER_ID INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    CATEGORY_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50) NOT NULL
);
CREATE TABLE billS (
    BILL_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    BILL_TIME DATETIME NOT NULL,
    PLACE VARCHAR(50) NOT NULL,
    CATEGORY_ID INT NOT NULL,
    FOREIGN KEY (CATEGORY_id) REFERENCES CATEGORIES(CATEGORY_ID),
    MONEY DECIMAL(10,2) NOT NULL,
    REMARK VARCHAR(256) NOT NULL
);